### ISSUE TITLE
Help please?

### ISSUE THREAD

**Issue by Isen1232** [kyleskom/NBA-Machine-Learning-Sports-Betting#149]
2023-03-14 14:46:58.406721: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-14 14:46:59.570341: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-03-14 14:46:59.570494: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-03-14 14:46:59.570513: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-03-14 14:47:01.261059: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

**Comment by milandijhon** [comment]
im getting the same error

**Comment by milandijhon** [comment]
my error:
I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Charlotte Hornets vs Cleveland Cavaliers:

**Comment by betevents** [comment]
try installing the latest rc2 tensorflow
python pip install tensorflow==2.12.0.rc1

or
python3 -m pip install tensorflow==2.12.0.rc1

**Comment by milandijhon** [comment]
I been fighting this keras issue all night, can someone HELP?

PS C:\Users\BNard\Documents\GitHub\NBA-Machine-Learning-Sports-Betting>  & 'C:\Users\BNard\AppData\Local\Microsoft\WindowsApps\python3.10.exe' 'c:\Users\BNard\.vscode\extensions\ms-python.python-2023.5.10741016\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '60085' '--' 'C:\Users\BNard\Documents\GitHub\NBA-Machine-Learning-Sports-Betting\main.py'
C:\Users\BNard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\keras\saving\legacy\saved_model\load.py:110: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  metadata.ParseFromString(file_content)
Cleveland Cavaliers vs Philadelphia 76ers:    The program just freezes at this point.    unistalled and reinstalled  the code, keras and tensorflow. any ideas?

**Comment by kyleskom** [comment]
What command are you using to run that?

**Comment by milandijhon** [comment]
python main.py
    On Wednesday, March 15, 2023 at 05:12:10 PM EDT, Kyle Skompinski ***@***.***> wrote:  
 
 


What command are you using to run that?

**Comment by kyleskom** [comment]
Try this `python main.py -A -odds=draftkings`

**Comment by milandijhon** [comment]
PS C:\Users\BNard\Documents\GitHub\NBA-Machine-Learning-Sports-Betting> python main.py -A -odds=draftkingsTraceback (most recent call last):  File "C:\Users\BNard\Documents\GitHub\NBA-Machine-Learning-Sports-Betting\main.py", line 3, in <module>    import pandas as pd  File "C:\Users\BNard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\__init__.py", line 48, in <module>    from pandas.core.api import (  File "C:\Users\BNard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\core\api.py", line 22, in <module>    from pandas.core.algorithms import (  File "C:\Users\BNard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\core\algorithms.py", line 40, in <module>    from pandas.core.dtypes.cast import (  File "C:\Users\BNard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\core\dtypes\cast.py", line 23, in <module>    from dateutil.parser import ParserErrorImportError: cannot import name 'ParserError' from 'dateutil.parser' (C:\Users\BNard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dateutil\parser\__init__.py)
   On Wednesday, March 15, 2023 at 05:17:14 PM EDT, Kyle Skompinski ***@***.***> wrote:  
 
 


Try this python main.py -A -odds=draftkings

**Comment by milandijhon** [comment]
came back with  pip install --upgrade python-dateutil and it worked.
    thanks so much!!!!

    On Wednesday, March 15, 2023 at 05:21:02 PM EDT, Bernard Sanders ***@***.***> wrote:  
 
 PS C:\Users\BNard\Documents\GitHub\NBA-Machine-Learning-Sports-Betting> python main.py -A -odds=draftkingsTraceback (most recent call last):  File "C:\Users\BNard\Documents\GitHub\NBA-Machine-Learning-Sports-Betting\main.py", line 3, in <module>    import pandas as pd  File "C:\Users\BNard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\__init__.py", line 48, in <module>    from pandas.core.api import (  File "C:\Users\BNard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\core\api.py", line 22, in <module>    from pandas.core.algorithms import (  File "C:\Users\BNard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\core\algorithms.py", line 40, in <module>    from pandas.core.dtypes.cast import (  File "C:\Users\BNard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\core\dtypes\cast.py", line 23, in <module>    from dateutil.parser import ParserErrorImportError: cannot import name 'ParserError' from 'dateutil.parser' (C:\Users\BNard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dateutil\parser\__init__.py)
   On Wednesday, March 15, 2023 at 05:17:14 PM EDT, Kyle Skompinski ***@***.***> wrote:  
 
 


Try this python main.py -A -odds=draftkings
